#!/bin/bash

# GridCloud Landing - Akash Wallet Setup Script
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
AKASH_CHAIN_ID="akashnet-2"
AKASH_NODE="https://rpc.akashnet.net:443"

echo -e "${BLUE}🔑 GridCloud Landing - Akash Wallet Setup${NC}"
echo "=============================================="

# Function to create .env file
create_env_file() {
    local wallet_name=$1
    local wallet_address=$2
    
    cat > .akash/.env << EOF
# Akash Wallet Configuration
# This file is automatically generated and should not be committed to git
AKASH_KEY_NAME=$wallet_name
AKASH_KEYRING_BACKEND=test
AKASH_CHAIN_ID=akashnet-2
AKASH_NODE=https://rpc.akashnet.net:443

# Wallet Info
AKASH_WALLET_ADDRESS=$wallet_address

# GitHub Container Registry (required for private images)
# Set your GitHub Personal Access Token here
GITHUB_PAT=
EOF
    
    echo -e "${BLUE}📄 Created .akash/.env file${NC}"
}

# Check if akash CLI is installed
if ! command -v akash &> /dev/null; then
    echo -e "${RED}❌ Akash CLI not found. Please run ./deploy.sh first to install it.${NC}"
    exit 1
fi

echo -e "${CYAN}Choose an option:${NC}"
echo "1. Import existing wallet (from mnemonic)"
echo "2. Create new wallet"
echo "3. List existing wallets"
echo "4. Check wallet balance"
echo ""

read -p "Enter your choice (1-4): " choice

case $choice in
    1)
        echo -e "${YELLOW}📥 Import Existing Wallet${NC}"
        echo "================================"
        
        read -p "Enter wallet name: " wallet_name
        
        if [ -z "$wallet_name" ]; then
            echo -e "${RED}❌ Wallet name cannot be empty${NC}"
            exit 1
        fi
        
        # Check if wallet already exists
        if akash keys show "$wallet_name" &> /dev/null; then
            echo -e "${YELLOW}⚠️  Wallet '$wallet_name' already exists${NC}"
            read -p "Do you want to overwrite it? (y/N): " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                echo "Operation cancelled."
                exit 0
            fi
            akash keys delete "$wallet_name" -y
        fi
        
        echo -e "${CYAN}Please enter your mnemonic phrase:${NC}"
        echo "(This will be hidden for security)"
        echo ""
        
        # Import wallet with mnemonic
        akash keys add "$wallet_name" --recover
        
        if [ $? -eq 0 ]; then
            echo -e "${GREEN}✅ Wallet '$wallet_name' imported successfully!${NC}"
            
            # Get wallet address (filter out warnings)
            wallet_address=$(akash keys show "$wallet_name" -a 2>/dev/null | grep -E '^akash[0-9a-z]+$')
            echo -e "${BLUE}📍 Wallet Address: $wallet_address${NC}"
            
            # Set environment variable
            echo -e "${YELLOW}🔧 Setting up environment...${NC}"
            
            # Create .env file
            create_env_file "$wallet_name" "$wallet_address"
            
            # Also add to ~/.bashrc for global access
            echo "export AKASH_KEY_NAME=$wallet_name" >> ~/.bashrc
            echo "export AKASH_KEYRING_BACKEND=test" >> ~/.bashrc
            export AKASH_KEY_NAME="$wallet_name"
            export AKASH_KEYRING_BACKEND="test"
            
            echo -e "${GREEN}✅ Environment configured!${NC}"
            echo ""
            echo -e "${CYAN}💡 To use in current session, run:${NC}"
            echo "source .akash/.env"
        else
            echo -e "${RED}❌ Failed to import wallet${NC}"
            exit 1
        fi
        ;;
        
    2)
        echo -e "${YELLOW}🆕 Create New Wallet${NC}"
        echo "========================="
        
        read -p "Enter wallet name: " wallet_name
        
        if [ -z "$wallet_name" ]; then
            echo -e "${RED}❌ Wallet name cannot be empty${NC}"
            exit 1
        fi
        
        # Check if wallet already exists
        if akash keys show "$wallet_name" &> /dev/null; then
            echo -e "${RED}❌ Wallet '$wallet_name' already exists${NC}"
            exit 1
        fi
        
        echo -e "${CYAN}Creating new wallet...${NC}"
        akash keys add "$wallet_name"
        
        if [ $? -eq 0 ]; then
            echo -e "${GREEN}✅ Wallet '$wallet_name' created successfully!${NC}"
            
            # Get wallet address (filter out warnings)
            wallet_address=$(akash keys show "$wallet_name" -a 2>/dev/null | grep -E '^akash[0-9a-z]+$')
            echo -e "${BLUE}📍 Wallet Address: $wallet_address${NC}"
            
            # Set environment variable
            echo -e "${YELLOW}🔧 Setting up environment...${NC}"
            
            # Create .env file
            create_env_file "$wallet_name" "$wallet_address"
            
            # Also add to ~/.bashrc for global access
            echo "export AKASH_KEY_NAME=$wallet_name" >> ~/.bashrc
            echo "export AKASH_KEYRING_BACKEND=test" >> ~/.bashrc
            export AKASH_KEY_NAME="$wallet_name"
            export AKASH_KEYRING_BACKEND="test"
            
            echo -e "${GREEN}✅ Environment configured!${NC}"
            echo ""
            echo -e "${CYAN}💡 To use in current session, run:${NC}"
            echo "source .akash/.env"
            
            echo ""
            echo -e "${YELLOW}⚠️  IMPORTANT: Save your mnemonic phrase securely!${NC}"
            echo "You'll need it to recover your wallet."
        else
            echo -e "${RED}❌ Failed to create wallet${NC}"
            exit 1
        fi
        ;;
        
    3)
        echo -e "${YELLOW}📋 Existing Wallets${NC}"
        echo "==================="
        
        wallets=$(akash keys list --output json 2>/dev/null)
        
        if [ -z "$wallets" ] || [ "$wallets" = "[]" ]; then
            echo -e "${YELLOW}No wallets found${NC}"
        else
            echo "$wallets" | jq -r '.[] | "Name: \(.name) | Address: \(.address)"'
        fi
        
        echo ""
        if [ ! -z "$AKASH_KEY_NAME" ]; then
            echo -e "${GREEN}Current active wallet: $AKASH_KEY_NAME${NC}"
        else
            echo -e "${YELLOW}No active wallet set${NC}"
        fi
        ;;
        
    4)
        echo -e "${YELLOW}💰 Check Wallet Balance${NC}"
        echo "========================"
        
        if [ -z "$AKASH_KEY_NAME" ]; then
            echo -e "${RED}❌ AKASH_KEY_NAME not set${NC}"
            echo "Please set your wallet first or run option 1/2"
            exit 1
        fi
        
        wallet_address=$(akash keys show "$AKASH_KEY_NAME" -a 2>/dev/null | grep -E '^akash[0-9a-z]+$')
        
        if [ -z "$wallet_address" ]; then
            echo -e "${RED}❌ Wallet '$AKASH_KEY_NAME' not found${NC}"
            exit 1
        fi
        
        echo -e "${BLUE}📍 Wallet: $AKASH_KEY_NAME${NC}"
        echo -e "${BLUE}📍 Address: $wallet_address${NC}"
        echo ""
        echo -e "${CYAN}💰 Checking balance...${NC}"
        
        balance=$(akash query bank balances "$wallet_address" --node "$AKASH_NODE" --chain-id "$AKASH_CHAIN_ID" 2>/dev/null)
        
        if [ $? -eq 0 ]; then
            echo "$balance"
            
            # Check if has sufficient balance for deployment (look specifically for uakt)
            uakt_balance=$(echo "$balance" | grep -A1 '"denom": "uakt"' | grep '"amount"' | grep -o '[0-9]*')
            
            if [ ! -z "$uakt_balance" ] && [ "$uakt_balance" -gt 5000000 ]; then
                echo -e "${GREEN}✅ Sufficient balance for deployment!${NC}"
            else
                echo -e "${YELLOW}⚠️  Low balance. Minimum ~5 AKT recommended for deployment${NC}"
                echo -e "${CYAN}💡 Fund your wallet at: https://app.osmosis.zone${NC}"
            fi
        else
            echo -e "${RED}❌ Failed to check balance${NC}"
        fi
        ;;
        
    *)
        echo -e "${RED}❌ Invalid choice${NC}"
        exit 1
        ;;
esac

echo ""
echo -e "${GREEN}🎉 Wallet setup complete!${NC}"
echo ""
echo -e "${CYAN}Next steps:${NC}"
echo "1. Fund your wallet with AKT tokens (minimum ~5 AKT)"
echo "2. Run: ./deploy.sh to deploy your application"
echo ""
echo -e "${BLUE}💡 Useful commands:${NC}"
echo "• Check balance: akash query bank balances \$(akash keys show \$AKASH_KEY_NAME -a 2>/dev/null | grep -E '^akash[0-9a-z]+$') --node $AKASH_NODE --chain-id $AKASH_CHAIN_ID"
echo "• List wallets: akash keys list"
echo "• Show address: akash keys show \$AKASH_KEY_NAME -a 2>/dev/null | grep -E '^akash[0-9a-z]+$'"
